Repository openshift-eng/elliott, pull requests merged in 2018-12, with the labels that each got.

#4 override certifi ca bundle in favor of the system CA bundle which has…
  elliottlib/errata.py
Labels: size/XS

#5 Update elliott to use gitdata module
  elliottlib/constants.py
  elliottlib/image.py
  elliottlib/metadata.py
  elliottlib/rpmcfg.py
  elliottlib/runtime.py
  requirements.txt
Labels: size/L

#6 Remove all hardcoded bugzilla values
  elliott
  elliottlib/bugzilla.py
  elliottlib/constants.py
Labels: size/M

#7 Move errata tool template information out of code
  elliott
  elliottlib/constants.py
  elliottlib/errata.py
Labels: size/M

#8 Add information about et and bz templates
  README.md
Labels: size/L
