Repository openshift-eng/elliott, pull requests merged in 2019-03, with the labels that each got.

#15 Enable security advisory workflow
  elliott
  elliottlib/bzutil.py
  elliottlib/constants.py
  elliottlib/errata.py
  elliottlib/util.py
Labels: size/L

#16 Add default values in bug searches
  elliottlib/bzutil.py
Labels: lgtm, size/XS

#19 fix change-state bug+lint errors
  elliott
Labels: ok-to-test, size/M

#20 fix ET addBuilds + lint warnings
  elliott
Labels: ok-to-test, size/S

#18 schema_group.yml: add use_source_fallback_branch
  elliottlib/schema_group.yml
Labels: size/XS

#21 Fix unsafe yaml loading
  elliottlib/runtime.py
Labels: lgtm, size/XS

#22 Fix error handling
  elliott
Labels: lgtm, size/M

#23 Correct exception handling for kerb
  elliott
  elliottlib/errata.py
Labels: lgtm, size/S
