Repository openshift-eng/elliott, pull requests merged in 2019-05, with the labels that each got.

#41 Update find-bugs and find-builds for payload diffs
  elliott
  elliottlib/openshiftclient.py
Labels: lgtm, size/L

#37 enable using default advisories, expose more errata info
  elliott
  elliottlib/runtime.py
  requirements.txt
Labels: size/L

#43 Fix flagging bugs
  elliott
Labels: lgtm, size/XS

#44 Cross-verify payload and advisory builds
  elliott
  elliottlib/VERSION
  elliottlib/errata.py
  elliottlib/util.py
Labels: size/L
