Repository openshift-eng/elliott, pull requests merged in 2019-06, with the labels that each got.

#47 [ART-544] (part 1 of 4) Config tox to run flake and unit tests
  .gitignore
  tox.ini
Labels: lgtm, size/S

#48 [ART-544] (part 2 of 4) Make flake8 happy ;D
  elliottlib/assertion.py
  elliottlib/brew.py
  elliottlib/bzutil.py
  elliottlib/bzutil_test.py
  elliottlib/config.py
  elliottlib/container_test.py
  elliottlib/errata.py
  elliottlib/errata_test.py
  elliottlib/exceptions.py
  elliottlib/image.py
  elliottlib/image_test.py
  elliottlib/metadata.py
  elliottlib/metadata_test.py
  elliottlib/model.py
  elliottlib/openshiftclient.py
  elliottlib/rpmcfg.py
  elliottlib/rpmcfg_test.py
  elliottlib/runtime.py
  elliottlib/util.py
Labels: size/L

#49 [ART-544] (part 3 of 4) Make current tests pass
  elliottlib/brew.py
  elliottlib/brew_test.py
  elliottlib/container_test.py
  elliottlib/errata.py
  elliottlib/errata_test.py
  elliottlib/exectools_test.py
  elliottlib/image_test.py
  elliottlib/metadata_test.py
  elliottlib/rpmcfg_test.py
  elliottlib/runtime.py
Labels: size/S

#50 [ART-544] (part 4 of 4) Run `tox` on Travis
  .ci/Dockerfile
  .travis.yml
Labels: size/S

#51 Move unit tests outside elliottlib module
  tests/assertion_test.py
  tests/brew_test.py
  tests/bzutil_test.py
  tests/cli_opts_test.py
  tests/container_test.py
  tests/errata_test.py
  tests/exectools_test.py
  tests/image_test.py
  tests/metadata_test.py
  tests/pushd_test.py
  tests/rpmcfg_test.py
  tests/runtime_test.py
  tests/test_structures.py
  tox.ini
Labels: size/XS

#42 List installation dependencies on README
  README.md
Labels: lgtm, size/XS

#52 Turn tests into a module for better organization
  tests/__init__.py
  tests/test_assertion.py
  tests/test_brew.py
  tests/test_bzutil.py
  tests/test_cli.py
  tests/test_container.py
  tests/test_errata.py
  tests/test_exectools.py
  tests/test_image.py
  tests/test_metadata.py
  tests/test_pushd.py
  tests/test_rpmcfg.py
  tests/test_runtime.py
  tox.ini
Labels: size/XS

#46 correct misleading date format info
  elliott
  elliottlib/errata.py
  elliottlib/util.py
Labels: size/S
