Repository openshift-eng/elliott, pull requests merged in 2019-11, with the labels that each got.

#71 ART-1011 improve rhsa creation
  .devcontainer/settings.yaml
  elliottlib/bzutil.py
  elliottlib/cli/create_cli.py
  elliottlib/constants.py
  elliottlib/errata.py
  tests/test_bzutil.py
  tests/test_errata.py
Labels: size/L

#58 Update find-bugs to generate a report
  elliott
  elliottlib/bzutil.py
Labels: lgtm, size/S

#69 remove dead code
  elliottlib/constants.py
  elliottlib/container.py
  elliottlib/image.py
  elliottlib/imagecfg.py
  elliottlib/metadata.py
  elliottlib/rpmcfg.py
  elliottlib/runtime.py
  tests/test_container.py
  tests/test_image.py
Labels: lgtm, size/XL

#78 Embed pygitdata for future refactoring and Python 3 migration
  elliottlib/gitdata.py
  elliottlib/runtime.py
  requirements.txt
Labels: lgtm, size/L

#77 Refactoring: Move entrypoint to elliottlib/cli/__main__.py
  .devcontainer/devcontainer.json
  elliott
  elliottlib/cli/__main__.py
  requirements-dev.txt
  setup.py
  tox.ini
Labels: lgtm, size/XXL

#80 Refactor unit test imports for Python 3 migration
  tests/test_assertion.py
  tests/test_brew.py
  tests/test_cli.py
  tests/test_errata.py
  tests/test_exectools.py
  tests/test_imagecfg.py
  tests/test_pushd.py
  tests/test_runtime.py
Labels: size/M

#87 adding oc client into dev container
  .devcontainer/dev.Dockerfile
  .devcontainer/devcontainer.json
Labels: lgtm, size/S

#86 ART-1154: Show RPMDiff failures for an advisory
  elliott
  elliottlib/cli/__main__.py
  elliottlib/cli/rpmdiff_cli.py
  elliottlib/constants.py
  elliottlib/errata.py
  elliottlib/rpmdiff.py
  tests/test_errata.py
  tests/test_rpmdiff.py
Labels: size/L

#89 [ART-1246] fix bugs some errata return product_version types are not consistent…
  elliottlib/cli/find_builds_cli.py
Labels: size/XS

#90 [ART-670] Generate Image List for CCS (docs team)
  elliottlib/cli/__main__.py
  elliottlib/cli/advisory_images_cli.py
  elliottlib/constants.py
  elliottlib/errata.py
  tests/test_errata.py
Labels: lgtm, size/L

#92 Cherry-pick python3 changes onto master
  elliottlib/__init__.py
  elliottlib/assertion.py
  elliottlib/brew.py
  elliottlib/bzutil.py
  elliottlib/cli/__main__.py
  elliottlib/cli/create_cli.py
  elliottlib/cli/list_cli.py
  elliottlib/cli_opts.py
  elliottlib/config.py
  elliottlib/constants.py
  elliottlib/dotconfig.py
  elliottlib/errata.py
  elliottlib/exceptions.py
  elliottlib/exectools.py
  elliottlib/gitdata.py
  elliottlib/imagecfg.py
  elliottlib/logutil.py
  elliottlib/metadata.py
  elliottlib/model.py
  elliottlib/openshiftclient.py
  elliottlib/pushd.py
  elliottlib/rpmcfg.py
  elliottlib/runtime.py
  elliottlib/tarball_sources.py
  elliottlib/util.py
  setup.py
  tests/test_assertion.py
  tests/test_brew.py
  tests/test_bzutil.py
  tests/test_cli.py
  tests/test_errata.py
  tests/test_exectools.py
  tests/test_find_builds_cli.py
  tests/test_imagecfg.py
  tests/test_pushd.py
  tests/test_runtime.py
  tests/test_structures.py
  tests/test_util.py
Labels: size/L

#94 Fix rpmdiff list waivers API call
  elliottlib/cli/rpmdiff_cli.py
  elliottlib/rpmdiff.py
  tests/test_rpmdiff.py
Labels: size/S

#95 Update dev container configuration
  .devcontainer/dev.Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/krb5-redhat.conf
  requirements-dev.txt
Labels: lgtm, size/M
