Repository openshift-eng/elliott, pull requests merged in 2019-12, with the labels that each got.

#102 License dotconfig and gitdata under LGPL v3
  README.md
  elliottlib/dotconfig.py
  elliottlib/gitdata.py
Labels: lgtm, size/S

#101 temp fix for pygit2
  requirements.txt
Labels: size/XS

#99 Pass debug option down
  elliottlib/cli/__main__.py
Labels: lgtm, size/XS

#85 python 3 - compatiblity fixes
  elliottlib/cli/__main__.py
  elliottlib/cli_opts.py
  elliottlib/config.py
  elliottlib/dotconfig.py
  elliottlib/errata.py
  elliottlib/gitdata.py
  elliottlib/model.py
  elliottlib/openshiftclient.py
  elliottlib/runtime.py
  tests/test_assertion.py
  tests/test_brew.py
  tests/test_errata.py
  tests/test_tarball_sources.py
Labels: lgtm, size/M
