Repository openshift-eng/elliott, pull requests merged in 2019-04, with the labels that each got.

#24 Fix further unsafe yaml loading.
  elliottlib/config.py
Labels: lgtm, size/XS

#25 Get brew tag from group branch
  elliott
Labels: lgtm, size/XS

#26 Update OWNERS
  OWNERS
Labels: size/XS

#29 add multiple builds to errata
  elliott
Labels: needs-ok-to-test, size/XS

#30 Elliott can use a default advisory if defined in ocp-build-data
  elliott
  elliottlib/schema_group.yml
Labels: lgtm, size/M

#31 Fix repair-bugs command
  elliott
Labels: lgtm, size/M

#35 add --id parse support comma
  .gitignore
  elliott
  elliottlib/cli_opts.py
  elliottlib/cli_opts_test.py
Labels: size/M

#36 Repair-bugs: New options, doc refresh, and speed improvements.
  elliott
Labels: lgtm, size/L

#39 Version bump. Includes doc, usge, and speed enhancements to `repair-bugs`
  elliottlib/VERSION
Labels: size/XS
