Repository openshift-eng/elliott, pull requests merged in 2019-10, with the labels that each got.

#56 [ART-1091] Filter already attached image builds
  elliott
Labels: size/XS

#57 Refactor find_builds and fix some minor things
  elliott
  elliottlib/cli/common.py
  elliottlib/cli/find_builds_cli.py
  elliottlib/constants.py
  elliottlib/util.py
Labels: size/XL

#64 ART-1062 adding find-builds suport attach multiple images with different pv
  elliottlib/brew.py
  elliottlib/cli/find_builds_cli.py
  elliottlib/config.py
  elliottlib/image.py
  elliottlib/runtime.py
Labels: size/M

#72 [ART-1162] fix find-builds --between
  elliottlib/openshiftclient.py
Labels: lgtm, size/S

#66 Always pull latest CI image
  Jenkinsfile
Labels: lgtm, size/XS

#70 Move create, create-placeholder, and add_metadata commands to cli submodule
  elliott
  elliottlib/cli/add_metadata_cli.py
  elliottlib/cli/create_cli.py
  elliottlib/cli/create_placeholder_cli.py
Labels: lgtm, size/XL

#67 Move elliott 'list' commands into cli
  elliott
  elliottlib/cli/list_cli.py
Labels: lgtm, size/M

#73 ART-1192: Fix RHSA creation when no severity set on the tracking bug
  elliottlib/bzutil.py
  elliottlib/cli/create_cli.py
  elliottlib/constants.py
  elliottlib/errata.py
  tests/test_bzutil.py
Labels: size/L

#74 ART-1069: elliott puddle-advisories misses some advisory metadata
  elliott
  elliottlib/cli/puddle_advisories_cli.py
  elliottlib/constants.py
  elliottlib/errata.py
Labels: size/L

#65 Set correct permissions on rcm-guest for tarball sources
  elliottlib/cli/tarball_sources_cli.py
Labels: lgtm, size/XS

#61 ART-1021 Fix the version unmatched
  elliottlib/brew.py
  elliottlib/cli/find_builds_cli.py
  elliottlib/util.py
  tests/test_find_builds_cli.py
Labels: size/L

#75 Embed pydotconfig into elliott
  elliottlib/cli/common.py
  elliottlib/dotconfig.py
  requirements.txt
Labels: size/L

#76 Python 3: Create python-3 branch for migration
  README.md
  tox.ini
Labels: size/XS
