Repository openshift-eng/elliott, pull requests merged in 2020-02, with the labels that each got.

#111 refactor: to make find-builds rpm using brew API calls instead of com…
  elliottlib/brew.py
  elliottlib/cli/find_builds_cli.py
  elliottlib/errata.py
  tests/test_brew.py
Labels: lgtm, size/L

#114 [ART-1312] Drop Python2 support
  setup.py
  tox.ini
Labels: lgtm, size/XS

#117 [ART-1361] boilerplates key will always exist on file, regardless of GA impetus
  elliottlib/errata.py
Labels: size/XS
