Repository openshift-eng/elliott, pull requests merged in 2020-01, with the labels that each got.

#105 Add functional tests
  elliottlib/cli/rpmdiff_cli.py
  functional_tests/README.md
  functional_tests/__init__.py
  functional_tests/constants.py
  functional_tests/test_advisory_images.py
  functional_tests/test_change_state.py
  functional_tests/test_create.py
  functional_tests/test_find_bugs.py
  functional_tests/test_find_builds.py
  functional_tests/test_find_cve_trackers.py
  functional_tests/test_get.py
  functional_tests/test_list.py
  functional_tests/test_poll_signed.py
  functional_tests/test_rpmdiff.py
  functional_tests/test_tarball_sources.py
  functional_tests/test_verify_payload.py
  setup.py
  tox.ini
Labels: size/L

#104 Fully Migrate to Python 3 and cleanup some dead code
  .devcontainer/dev.Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yaml
  elliottlib/VERSION
  elliottlib/__init__.py
  elliottlib/assertion.py
  elliottlib/brew.py
  elliottlib/bzutil.py
  elliottlib/cli/__main__.py
  elliottlib/cli/add_metadata_cli.py
  elliottlib/cli/advisory_images_cli.py
  elliottlib/cli/cli_opts.py
  elliottlib/cli/common.py
  elliottlib/cli/create_cli.py
  elliottlib/cli/create_placeholder_cli.py
  elliottlib/cli/find_builds_cli.py
  elliottlib/cli/list_cli.py
  elliottlib/cli/puddle_advisories_cli.py
  elliottlib/cli/rpmdiff_cli.py
  elliottlib/cli/tarball_sources_cli.py
  elliottlib/config.py
  elliottlib/constants.py
  elliottlib/dotconfig.py
  elliottlib/errata.py
  elliottlib/exceptions.py
  elliottlib/exectools.py
  elliottlib/gitdata.py
  elliottlib/imagecfg.py
  elliottlib/logutil.py
  elliottlib/metadata.py
  elliottlib/model.py
  elliottlib/openshiftclient.py
  elliottlib/pushd.py
  elliottlib/rpmcfg.py
  elliottlib/rpmdiff.py
  elliottlib/runtime.py
  elliottlib/schema_group.yml
  elliottlib/schema_image.yml
  elliottlib/schema_rpm.yml
  elliottlib/tarball_sources.py
  elliottlib/util.py
  requirements.txt
  setup.py
  tests/test_assertion.py
  tests/test_brew.py
  tests/test_bzutil.py
  tests/test_cli.py
  tests/test_errata.py
  tests/test_exectools.py
  tests/test_runtime.py
  tests/test_tarball_sources.py
  tox.ini
Labels: size/XXL

#106 [ART-818] New "get advisory impetus" CLI command
  elliottlib/cli/__main__.py
  elliottlib/cli/advisory_impetus_cli.py
Labels: lgtm, size/M

#96 [ART-1342] speed up get_latest_build_info and solve the multi branch/tag mapping issue
  elliottlib/brew.py
  elliottlib/cli/find_builds_cli.py
  elliottlib/imagecfg.py
Labels: lgtm, size/M

#107 Additional fixes for better Python 2/3 compatibility
  elliottlib/brew.py
  elliottlib/bzutil.py
  elliottlib/cli/__main__.py
  elliottlib/cli/create_cli.py
  elliottlib/cli/puddle_advisories_cli.py
  elliottlib/cli/rpmdiff_cli.py
  elliottlib/dotconfig.py
  elliottlib/errata.py
  elliottlib/exectools.py
  elliottlib/gitdata.py
  elliottlib/model.py
  elliottlib/runtime.py
  elliottlib/tarball_sources.py
  functional_tests/test_find_bugs.py
  functional_tests/test_find_cve_trackers.py
  functional_tests/test_poll_signed.py
  functional_tests/test_rpmdiff.py
  requirements.txt
Labels: lgtm, size/M

#108 [ART-1176] refactoring elliott find_builds_cli.py bug fixes and removing branch option and product_version
  elliottlib/brew.py
  elliottlib/cli/__main__.py
  elliottlib/cli/add_metadata_cli.py
  elliottlib/cli/create_placeholder_cli.py
  elliottlib/cli/find_builds_cli.py
  elliottlib/util.py
  tests/test_errata.py
  tests/test_find_builds_cli.py
  tests/test_util.py
Labels: lgtm, size/L

#109 Fix missing koji import
  elliottlib/brew.py
Labels: size/XS

#112 Update Dev Container
  .devcontainer/dev.Dockerfile
Labels: lgtm, size/XS

#113 ART-1491: Fix elliott sweep by build claims no builds need to be added
  elliottlib/brew.py
  elliottlib/cli/find_builds_cli.py
  elliottlib/cli/tarball_sources_cli.py
  elliottlib/tarball_sources.py
  tests/test_brew.py
  tests/test_tarball_sources.py
Labels: size/L
