Repository openshift-eng/elliott, pull requests merged in 2021-04, with the labels that each got.

#184 [ART-2801] Add --verify-bug-status to verify_attached_bugs
  elliottlib/attach_cve_flaws.py
  elliottlib/cli/verify_attached_bugs_cli.py
Labels: lgtm

#185 Deprecate legacy CA
  .devcontainer/brewkoji.conf
Labels: lgtm

#186 Show existing and new bugs when sweeping
  elliottlib/cli/attach_cve_flaws_cli.py
  elliottlib/errata.py
Labels: lgtm, merge-post-promote

#187 Sweep builds by brew event
  elliottlib/brew.py
  elliottlib/cli/find_builds_cli.py
  tests/test_brew.py
Labels: merge-post-promote
